spring:
  application:
    name: GateWay
  cloud:
#    gateway:
#      routes:
#        - id: test-id-1
#          uri: http://www.baidu.com
#          predicates:
#            - Method=GET
#        - id: test-id-2
#          uri: http://127.0.0.1:9090/api/v1
#          predicates:
#            - Path=/**
#          filters:
#            - PrefixPath=/app/**
#    nacos:
#      config:
#        file-extension: yaml
#        group: DEFAULT_GROUP
#        name: gateway
#        namespace: 0f5c3cf2-9b02-4e04-8b02-ef10439aba82
#        prefix: ${spring.application.name}
#        refresh-enabled: true
#        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
