spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: bserver
          uri: lb://bserver
          predicates:
            - Path=/bserver/**
          filters:
            - StripPrefix=1

#    nacos:
#      config:
#        file-extension: yaml
#        group: DEFAULT_GROUP
#        name: gateway
#        namespace: 0f5c3cf2-9b02-4e04-8b02-ef10439aba82
#        prefix: ${spring.application.name}
#        refresh-enabled: true
#        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848



#熔断器配置
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE
#          thread:
#            timeoutInMilliseconds: 3000
#  shareSecurityContext: true

#网关日志输出
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG


yt:
  allow:
    paths:
      - /api/v1
      - /api/v2
      - /test
